# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run lint and tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Test code with custom test engine for HW1
      run: |
        cd HW1
        python -m src.main -g ALL > out/script.out       
        failureStr=$(python -m src.main -g ALL | grep -i "Number of failed tests:")
        numFailures=${failureStr:0-1}
        if [ $numFailures -gt 0 ]; then exit $numFailures; else exit 0; fi
    - name: Test code with custom test engine for HW2
      run: |
        cd HW2
        python -m src.main -g ALL > out/script.out       
        failureStr=$(python -m src.main -g ALL | grep -i "Number of failed tests:")
        numFailures=${failureStr:0-1}
        if [ $numFailures -gt 0 ]; then exit $numFailures; else exit 0; fi
    - name: Test code with custom test engine for HW3
      run: |
        cd HW3
        python -m src.main -g ALL > out/script.out       
        failureStr=$(python -m src.main -g ALL | grep -i "Number of failed tests:")
        numFailures=${failureStr:0-1}
        if [ $numFailures -gt 0 ]; then exit $numFailures; else exit 0; fi  